# Generated by Django 4.1.3 on 2023-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=54)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'FEMALE')], max_length=25)),
                ('course', models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA')], max_length=25)),
            ],
        ),
    ]
