# Generated by Django 4.1.3 on 2023-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_registration_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA')], default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'FEMALE')], default=True, max_length=25),
        ),
    ]
