# Generated by Django 4.1.3 on 2023-01-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_registration_course_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
