# Generated by Django 4.1.3 on 2023-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
